// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo6NcbNC-CYa288rE6gqZieebdwu2tmEU',
    appId: '1:704400446551:web:6cc9f60dddfb5ddf757f12',
    messagingSenderId: '704400446551',
    projectId: 'canto-do-baby',
    authDomain: 'canto-do-baby.firebaseapp.com',
    storageBucket: 'canto-do-baby.firebasestorage.app',
    measurementId: 'G-JZXW89YQRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBevfcp7qhpYVr2JP6sfy5DU1kfiH21tEQ',
    appId: '1:704400446551:android:5b1ed6afbf84be10757f12',
    messagingSenderId: '704400446551',
    projectId: 'canto-do-baby',
    storageBucket: 'canto-do-baby.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNRHS31eh5CsRhyfkvvNewsM42zDT8_WY',
    appId: '1:704400446551:ios:90c9069554b7a287757f12',
    messagingSenderId: '704400446551',
    projectId: 'canto-do-baby',
    storageBucket: 'canto-do-baby.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNRHS31eh5CsRhyfkvvNewsM42zDT8_WY',
    appId: '1:704400446551:ios:90c9069554b7a287757f12',
    messagingSenderId: '704400446551',
    projectId: 'canto-do-baby',
    storageBucket: 'canto-do-baby.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo6NcbNC-CYa288rE6gqZieebdwu2tmEU',
    appId: '1:704400446551:web:cd2c86f4c9930e29757f12',
    messagingSenderId: '704400446551',
    projectId: 'canto-do-baby',
    authDomain: 'canto-do-baby.firebaseapp.com',
    storageBucket: 'canto-do-baby.firebasestorage.app',
    measurementId: 'G-SDF6XH7WEE',
  );
}
